<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.0-beta-30</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A package designed to make starting up an connection with SNI easier.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FeTracker.Common" Version="2.0.0-beta-30" />
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
	  <Content Include="Protos\sni.proto" Pack="true" Visible="true" />
    <Folder Include="Protos\" />
	  <Protobuf Include="Protos\sni.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
	<None Include="README.md">
	  <Pack>True</Pack>
	  <PackagePath>\</PackagePath>
	</None>
  </ItemGroup>

</Project>
